#!/usr/bin/env python3
"""Draw the profile's SVG assets. Python 3.10+, standard library, no network."""
from __future__ import annotations

import argparse
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
THEMES = {
    'dark': dict(bg='#0d1117', panel='#111823', grid='#182230', line='#364459',
                 ink='#eef2f9', muted='#aab7ca', accent='#8a9cff', wash='#1b2545'),
    'light': dict(bg='#ffffff', panel='#f8faff', grid='#edf1f8', line='#bac5d7',
                  ink='#172034', muted='#53627a', accent='#1024d0', wash='#edf0ff'),
}
TITLES = {'gds': 'GDS', 'ai-stp': 'ai-stp', 'setup': 'Setup systems', 'nddev': 'NDDev'}
DESCRIPTIONS = {
    'gds': 'Canonical source passes through a policy and context compiler into an immutable bundle and repository-local projections. Repository identity is separate from checkout location.',
    'ai-stp': 'The CLI assembles a bundle. The provider, not the CLI, writes the native harness state. A project of AI Engineers Guild.',
    'setup': 'The target is backed up before a change is applied and verified. A saved backup provides a separate restore path to the target.',
    'nddev': 'Six divisions: Dev, AI, Design, R&D, Platform and OpenNetwork.',
}


class Drawing:
    """Small, explicit SVG vocabulary; all coordinates remain reviewable."""
    def __init__(self, width: int, height: int, theme: str, title: str, desc: str):
        self.w, self.h, self.c = width, height, THEMES[theme]
        c = self.c
        self.parts = [
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-labelledby="title desc">',
            f'<title id="title">{escape(title)}</title><desc id="desc">{escape(desc)}</desc>',
            '<!-- Generated by tools/render_profile.py. Edit the drawing source, not this file. -->',
            f'<defs><pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M24 0H0V24" fill="none" stroke="{c["grid"]}"/></pattern>',
            f'<marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto" markerUnits="userSpaceOnUse"><path d="m2 1 5 3-5 3" fill="none" stroke="{c["accent"]}" stroke-width="1.5"/></marker></defs>',
            f'<rect x="1" y="1" width="{width-2}" height="{height-2}" rx="10" fill="{c["bg"]}" stroke="{c["line"]}"/>',
            f'<rect x="16" y="16" width="{width-32}" height="{height-32}" fill="url(#grid)" opacity=".7"/>',
        ]
        for x, y in ((16, 16), (width-16, 16), (16, height-16), (width-16, height-16)):
            self.path(f'M{x-4} {y}h8M{x} {y-4}v8', 'line', 1)

    def text(self, x: float, y: float, text: str, size: int = 22,
             color: str = 'ink', weight: int = 400, anchor: str = 'start', mono: bool = False):
        font = 'monospace' if mono else 'Arial, Helvetica, sans-serif'
        self.parts.append(f'<text x="{x}" y="{y}" font-family="{font}" font-size="{size}" font-weight="{weight}" text-anchor="{anchor}" fill="{self.c[color]}">{escape(text)}</text>')

    def rect(self, x: float, y: float, w: float, h: float, fill: str = 'panel', stroke: str = 'line', radius: int = 5):
        self.parts.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{radius}" fill="{self.c[fill]}" stroke="{self.c[stroke]}"/>')

    def path(self, d: str, color: str = 'accent', width: float = 1.6,
             arrow: bool = False, dashed: bool = False):
        extra = (' marker-end="url(#arrow)"' if arrow else '') + (' stroke-dasharray="5 5"' if dashed else '')
        self.parts.append(f'<path d="{d}" fill="none" stroke="{self.c[color]}" stroke-width="{width}" stroke-linecap="round" stroke-linejoin="round"{extra}/>')

    def node(self, x: int, y: int, w: int, title: str, sub: str = '', active: bool = False, small: bool = False):
        h = 66 if sub else 48
        self.rect(x, y, w, h, 'wash' if active else 'panel', 'accent' if active else 'line')
        self.path(f'M{x} {y+12}V{y}h12', width=2)
        self.text(x+w/2, y+(28 if sub else 32), title, 22 if small else 23, weight=600, anchor='middle')
        if sub:
            self.text(x+w/2, y+51, sub, 18, 'muted', anchor='middle')

    def stack(self, cx: int, cy: int, scale: float = 1):
        """Exploded repository sheets, not an invented product logo."""
        self.parts.append(f'<g transform="translate({cx} {cy}) scale({scale})">')
        for offset in (32, 16, 0):
            self.parts.append(f'<path d="M-68 {offset} 0 {offset-34} 68 {offset} 0 {offset+34}Z" fill="{self.c["panel"]}" stroke="{self.c["line"]}" stroke-width="1.5"/>')
        self.path('M-68 0 0 34 68 0', width=2)
        self.path('M-36 -4-10 9M-22 -11 15 8M-8 -18 34 3', 'muted', 1.5)
        self.path('M0 34v32', dashed=True)
        self.parts.append('</g>')

    def finish(self) -> str:
        return '\n'.join(self.parts + ['</svg>', ''])


def render(kind: str, theme: str, mobile: bool = False, motion: bool = False) -> str:
    w = 480 if mobile else 960
    heights = {'gds': (330, 410), 'ai-stp': (262, 352), 'setup': (300, 378), 'nddev': (234, 310)}
    h = heights[kind][int(mobile)]
    s = Drawing(w, h, theme, TITLES[kind], DESCRIPTIONS[kind])
    number = {'gds': '01', 'ai-stp': '02', 'setup': '03', 'nddev': '04'}[kind]
    s.text(32, 45, number, 16, 'accent', mono=True)
    s.text(76, 48, TITLES[kind], 32 if mobile else 36, weight=600)

    if kind == 'gds':
        s.text(32, 87, 'Repository control plane', 22, 'muted')
        if mobile:
            positions = [(32, 118), (262, 118), (262, 254), (32, 254)]
            width = 186
            labels = [('Source', 'identity + policy'), ('Compiler', 'policy + context'), ('Bundle', 'immutable output'), ('Repositories', 'local projections')]
            routes = ['M218 151H254', 'M355 184V246', 'M262 287H226']
            s.text(32, 374, 'Identity is not a path.', 22, 'muted')
        else:
            s.stack(784, 80, 1)
            s.path('M654 64v56m-10-46 10-10 10 10M914 96v-56m-10 46 10 10 10-10', 'line', 1)
            s.text(32, 133, 'One source. Local projections.', 25, weight=500)
            positions = [(32+232*i, 192) for i in range(4)]
            width = 200
            labels = [('Source', 'identity + policy'), ('Compiler', 'policy + context'), ('Bundle', 'immutable output'), ('Repositories', 'local projections')]
            routes = [f'M{232+232*i} 225H{256+232*i}' for i in range(3)]
            s.text(32, 301, 'Repository identity stays separate from checkout location.', 20, 'muted')
        for i, ((x, y), (title, sub)) in enumerate(zip(positions, labels)):
            s.node(x, y, width, title, sub, active=i == 1)
        for route in routes:
            s.path(route, arrow=True)
        if motion:
            # A finite accent, never essential content. The static paths remain visible.
            s.parts.append('<style>.signal{opacity:0;animation:flow 3.6s ease-in-out 1}@keyframes flow{0%{stroke-dashoffset:60;opacity:0}20%{opacity:1}80%{opacity:1}100%{stroke-dashoffset:0;opacity:0}}@media(prefers-reduced-motion:reduce){.signal{animation:none;opacity:0}}</style>')
            for route in routes:
                s.parts.append(f'<path class="signal" d="{route}" fill="none" stroke="{s.c["ink"]}" stroke-width="2" stroke-dasharray="8 52"/>')
    elif kind == 'ai-stp':
        s.text(32, 87, 'AI Engineers Guild', 22, 'muted')
        labels = [('CLI', 'assemble'), ('Bundle', 'exact versions'), ('Provider', 'write'), ('Harness', 'native state')]
        if mobile:
            positions = [(32, 116), (262, 116), (262, 246), (32, 246)]
            width = 186
            routes = ['M218 149H254', 'M355 182V238', 'M262 279H226']
        else:
            s.text(928, 49, 'ASSEMBLY / INSTALLATION', 15, 'muted', anchor='end', mono=True)
            positions = [(32+232*i, 124) for i in range(4)]
            width = 200
            routes = [f'M{232+232*i} 157H{256+232*i}' for i in range(3)]
            s.text(32, 234, 'The CLI assembles. Only the provider writes native state.', 20, 'muted')
        for i, ((x, y), (title, sub)) in enumerate(zip(positions, labels)):
            s.node(x, y, width, title, sub, active=i == 2)
        for route in routes:
            s.path(route, arrow=True)
    elif kind == 'setup':
        s.text(32, 87, 'Configuration lifecycle', 22, 'muted')
        if mobile:
            s.node(32, 112, 186, 'Target', active=True)
            s.node(262, 112, 186, 'Apply')
            s.node(262, 258, 186, 'Verify')
            s.node(32, 258, 186, 'Backup')
            s.path('M218 136H254', arrow=True)
            s.path('M355 160V250', arrow=True)
            s.path('M103 160V250', arrow=True)
            s.path('M147 258V168', arrow=True, dashed=True)
            s.text(32, 347, 'Back up first. Restore when needed.', 21, 'muted')
        else:
            s.text(928, 49, 'CHANGE / RECOVERY', 15, 'muted', anchor='end', mono=True)
            for x, title in [(32, 'Target'), (376, 'Apply'), (720, 'Verify')]:
                s.node(x, 120, 208, title, active=title == 'Target')
            s.path('M240 144H368', arrow=True)
            s.path('M584 144H712', arrow=True)
            s.node(32, 232, 208, 'Backup')
            s.path('M112 168V224', arrow=True)
            s.path('M168 232V176', arrow=True, dashed=True)
            s.text(192, 206, 'restore', 20, 'accent')
            s.text(376, 253, 'Back up before the change.', 22)
            s.text(376, 281, 'Keep a separate path back.', 20, 'muted')
    elif kind == 'nddev':
        s.text(32, 87, 'Six divisions. Hands-on engineering.', 21 if mobile else 22, 'muted')
        labels = ['Dev', 'AI', 'Design', 'R&D', 'Platform', 'OpenNetwork']
        if mobile:
            for i, label in enumerate(labels):
                s.node(32+(i % 2)*230, 114+(i // 2)*62, 186, label, small=True)
        else:
            s.path('M32 118H928', 'line', 1)
            for i, label in enumerate(labels):
                x, width = (32+i*140, 128) if i < 5 else (732, 196)
                s.path(f'M{x+width/2} 118v28', 'line', 1)
                s.node(x, 146, width, label, small=True)
    return s.finish()


def social() -> str:
    s = Drawing(1280, 640, 'dark', 'Danil Silantyev', 'AI Staff Engineer. Systems and AI Architect. OSS developer and contributor. CEO at NDDev.')
    s.text(64, 82, 'rldyourmnd', 23, 'accent', mono=True)
    s.text(64, 196, 'Danil', 80, weight=600)
    s.text(64, 287, 'Silantyev', 80, weight=600)
    s.text(64, 374, 'AI Staff Engineer', 32, weight=600)
    s.text(64, 423, 'Systems & AI Architect', 30, 'muted')
    s.text(64, 535, 'Open source. AI systems. Developer tools.', 24, 'muted')
    s.text(64, 579, 'CEO, NDDev', 23)
    s.stack(996, 204, 1.9)
    s.path('M996 330V374', arrow=True)
    for y, label in [(386, 'GDS'), (461, 'ai-stp'), (536, 'Setup systems')]:
        s.node(818, y, 356, label, active=label == 'GDS')
    return s.finish()


def expected_assets() -> dict[str, str]:
    result = {}
    for theme in THEMES:
        for mobile in (False, True):
            for kind in TITLES:
                name = f'{kind}-{theme}' + ('-mobile' if mobile else '') + '.svg'
                result[name] = render(kind, theme, mobile)
    for theme in THEMES:
        result[f'gds-{theme}-motion.svg'] = render('gds', theme, motion=True)
    result['social-preview.svg'] = social()
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Check exact output without writing.')
    parser.add_argument('--output', type=Path, default=ROOT/'assets/profile')
    args = parser.parse_args()
    assets = expected_assets()
    if args.check:
        errors = [name for name, data in assets.items()
                  if not (args.output/name).is_file() or (args.output/name).read_bytes() != data.encode('utf-8')]
        errors += sorted(p.name for p in args.output.glob('*.svg') if p.name not in assets)
        if errors:
            print('SVG drift: ' + ', '.join(errors))
            return 1
        print(f'PASS: {len(assets)} SVG assets reproduce byte-for-byte.')
    else:
        args.output.mkdir(parents=True, exist_ok=True)
        for name, data in assets.items():
            (args.output/name).write_bytes(data.encode('utf-8'))
        print(f'Wrote {len(assets)} SVG assets to {args.output}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
